import { Data, IProductInput } from "@/types";
import { toSlug } from "./utils";

// Disc images array - will cycle through these
const discImages = [
  '/Colossus.png',
  '/Condor.png',
  '/d-line-steady-bl-putt-approach-517688.png',
  '/images.png',
  '/IMG-0533.png',
  '/Neutron-Spin_2023_Green_1K.png',
  '/Odyssey_nxt_green_pink_gateway_disc_sports-34.png',
  '/Orc68b81.png',
  '/stinger_1800x1800.png',
  '/thread-alpha-250x250h.png',
  '/Time-Lapse_retooled_Neutron_Misprint.png',
  '/truth.png',
  '/ultra-star-white.png',
  '/Xero_feature.png',
]

// Helper to get image at index (cycles through array)
const getImage = (index: number) => discImages[index % discImages.length]

const products: IProductInput[] = [
  // Distance Drivers
  {
    name: 'Innova Destroyer',
    slug: toSlug('Innova Destroyer'),
    category: 'Distance Driver',
    images: [getImage(0), getImage(1)],
    tags: ['best-seller', 'featured'],
    discType: ['distance driver'],
    isPublished: true,
    price: 18.99,
    listPrice: 21.99,
    brand: 'Innova',
    plastic: 'Star',
    weight: 175,
    flightNumbers: { speed: 12, glide: 5, turn: -1, fade: 3 },
    avgRating: 4.8,
    numReviews: 156,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 3 },
      { rating: 3, count: 8 },
      { rating: 4, count: 28 },
      { rating: 5, count: 115 },
    ],
    numSales: 342,
    countInStock: 24,
    description:
      'The Destroyer is a fast, stable power driver with significant glide. Great for sidearm throwers and those with lots of power.',
    sizes: [],
    colors: ['Blue', 'Red', 'Yellow', 'Pink', 'Orange'],
    reviews: [],
  },
  {
    name: 'Discraft Zeus',
    slug: toSlug('Discraft Zeus'),
    category: 'Distance Driver',
    images: [getImage(1), getImage(2)],
    tags: ['new-arrival', 'featured'],
    discType: ['distance driver'],
    isPublished: true,
    price: 19.99,
    listPrice: 0,
    brand: 'Discraft',
    plastic: 'ESP',
    weight: 173,
    flightNumbers: { speed: 12, glide: 5, turn: -1, fade: 3 },
    avgRating: 4.7,
    numReviews: 89,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 5 },
      { rating: 4, count: 22 },
      { rating: 5, count: 59 },
    ],
    numSales: 187,
    countInStock: 18,
    description:
      'Paul McBeth signature distance driver. A stable to overstable driver with a pointed nose for reduced air resistance.',
    sizes: [],
    colors: ['Green', 'Blue', 'White', 'Black'],
    reviews: [],
  },
  {
    name: 'Dynamic Discs Sheriff',
    slug: toSlug('Dynamic Discs Sheriff'),
    category: 'Distance Driver',
    images: [getImage(2), getImage(3)],
    tags: ['todays-deal'],
    discType: ['distance driver'],
    isPublished: true,
    price: 15.99,
    listPrice: 18.99,
    brand: 'Dynamic Discs',
    plastic: 'Lucid',
    weight: 174,
    flightNumbers: { speed: 13, glide: 5, turn: -1, fade: 2 },
    avgRating: 4.5,
    numReviews: 67,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 3 },
      { rating: 3, count: 6 },
      { rating: 4, count: 18 },
      { rating: 5, count: 39 },
    ],
    numSales: 156,
    countInStock: 31,
    description:
      'The Sheriff is a high speed understable distance driver. Perfect for players looking for extra distance with less power.',
    sizes: [],
    colors: ['Orange', 'Purple', 'Teal', 'Yellow'],
    reviews: [],
  },
  {
    name: 'MVP Photon',
    slug: toSlug('MVP Photon'),
    category: 'Distance Driver',
    images: [getImage(3), getImage(4)],
    tags: ['new-arrival'],
    discType: ['distance driver'],
    isPublished: true,
    price: 21.99,
    listPrice: 0,
    brand: 'MVP',
    plastic: 'Neutron',
    weight: 172,
    flightNumbers: { speed: 11, glide: 5, turn: -1.5, fade: 2.5 },
    avgRating: 4.6,
    numReviews: 42,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 4 },
      { rating: 4, count: 12 },
      { rating: 5, count: 25 },
    ],
    numSales: 98,
    countInStock: 15,
    description:
      'The Photon is an overstable distance driver with GYRO technology. Excellent for headwind shots and reliable fade.',
    sizes: [],
    colors: ['Blue', 'Red', 'Green', 'White'],
    reviews: [],
  },
  // Fairway Drivers
  {
    name: 'Innova Thunderbird',
    slug: toSlug('Innova Thunderbird'),
    category: 'Fairway Driver',
    images: [getImage(4), getImage(5)],
    tags: ['best-seller'],
    discType: ['fairway driver'],
    isPublished: true,
    price: 17.99,
    listPrice: 0,
    brand: 'Innova',
    plastic: 'Champion',
    weight: 175,
    flightNumbers: { speed: 9, glide: 5, turn: 0, fade: 2 },
    avgRating: 4.9,
    numReviews: 203,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 5 },
      { rating: 4, count: 32 },
      { rating: 5, count: 163 },
    ],
    numSales: 421,
    countInStock: 28,
    description:
      'A power control fairway driver. The Thunderbird has a dependable high speed stability and a pointed nose.',
    sizes: [],
    colors: ['Red', 'Blue', 'Yellow', 'Pink'],
    reviews: [],
  },
  {
    name: 'Discraft Undertaker',
    slug: toSlug('Discraft Undertaker'),
    category: 'Fairway Driver',
    images: [getImage(5), getImage(6)],
    tags: ['featured'],
    discType: ['fairway driver'],
    isPublished: true,
    price: 18.99,
    listPrice: 22.99,
    brand: 'Discraft',
    plastic: 'Z Line',
    weight: 174,
    flightNumbers: { speed: 9, glide: 5, turn: -1, fade: 2 },
    avgRating: 4.7,
    numReviews: 78,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 6 },
      { rating: 4, count: 19 },
      { rating: 5, count: 51 },
    ],
    numSales: 167,
    countInStock: 22,
    description:
      'A straight flying fairway driver with a comfortable rim. Great for tunnel shots and controlled distance.',
    sizes: [],
    colors: ['Orange', 'Blue', 'Green', 'Pink'],
    reviews: [],
  },
  {
    name: 'Latitude 64 River',
    slug: toSlug('Latitude 64 River'),
    category: 'Fairway Driver',
    images: [getImage(6), getImage(7)],
    tags: ['todays-deal', 'best-seller'],
    discType: ['fairway driver'],
    isPublished: true,
    price: 14.99,
    listPrice: 17.99,
    brand: 'Latitude 64',
    plastic: 'Opto',
    weight: 173,
    flightNumbers: { speed: 7, glide: 7, turn: -1, fade: 1 },
    avgRating: 4.8,
    numReviews: 134,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 1 },
      { rating: 3, count: 7 },
      { rating: 4, count: 25 },
      { rating: 5, count: 100 },
    ],
    numSales: 289,
    countInStock: 35,
    description:
      'An easy to throw fairway driver with excellent glide. Perfect for beginners and experienced players alike.',
    sizes: [],
    colors: ['White', 'Blue', 'Yellow', 'Green'],
    reviews: [],
  },
  {
    name: 'Axiom Crave',
    slug: toSlug('Axiom Crave'),
    category: 'Fairway Driver',
    images: [getImage(7), getImage(8)],
    tags: ['new-arrival'],
    discType: ['fairway driver'],
    isPublished: true,
    price: 19.99,
    listPrice: 0,
    brand: 'Axiom',
    plastic: 'Plasma',
    weight: 170,
    flightNumbers: { speed: 6.5, glide: 5, turn: -1, fade: 1 },
    avgRating: 4.6,
    numReviews: 56,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 4 },
      { rating: 4, count: 15 },
      { rating: 5, count: 35 },
    ],
    numSales: 112,
    countInStock: 19,
    description:
      'A straight to understable fairway driver with GYRO technology. Great for controlled turnovers and straight shots.',
    sizes: [],
    colors: ['Purple', 'Pink', 'Blue', 'Orange'],
    reviews: [],
  },
  // Midranges
  {
    name: 'Discraft Buzzz',
    slug: toSlug('Discraft Buzzz'),
    category: 'Midrange',
    images: [getImage(8), getImage(9)],
    tags: ['best-seller', 'featured'],
    discType: ['midrange'],
    isPublished: true,
    price: 16.99,
    listPrice: 0,
    brand: 'Discraft',
    plastic: 'ESP',
    weight: 177,
    flightNumbers: { speed: 5, glide: 4, turn: -1, fade: 1 },
    avgRating: 4.9,
    numReviews: 287,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 3 },
      { rating: 3, count: 8 },
      { rating: 4, count: 34 },
      { rating: 5, count: 240 },
    ],
    numSales: 534,
    countInStock: 42,
    description:
      'The most popular midrange in disc golf. Dead straight with reliable fade. A must-have for any bag.',
    sizes: [],
    colors: ['Yellow', 'Blue', 'Orange', 'Green', 'Pink'],
    reviews: [],
  },
  {
    name: 'Innova Roc3',
    slug: toSlug('Innova Roc3'),
    category: 'Midrange',
    images: [getImage(9), getImage(10)],
    tags: ['best-seller'],
    discType: ['midrange'],
    isPublished: true,
    price: 15.99,
    listPrice: 18.99,
    brand: 'Innova',
    plastic: 'Champion',
    weight: 180,
    flightNumbers: { speed: 5, glide: 4, turn: 0, fade: 3 },
    avgRating: 4.7,
    numReviews: 178,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 4 },
      { rating: 3, count: 12 },
      { rating: 4, count: 38 },
      { rating: 5, count: 122 },
    ],
    numSales: 356,
    countInStock: 38,
    description:
      'A flat top version of the classic Roc. More overstable and perfect for headwinds and forehand shots.',
    sizes: [],
    colors: ['Red', 'Blue', 'White', 'Yellow'],
    reviews: [],
  },
  {
    name: 'MVP Hex',
    slug: toSlug('MVP Hex'),
    category: 'Midrange',
    images: [getImage(10), getImage(11)],
    tags: ['new-arrival', 'featured'],
    discType: ['midrange'],
    isPublished: true,
    price: 18.99,
    listPrice: 0,
    brand: 'MVP',
    plastic: 'Neutron',
    weight: 178,
    flightNumbers: { speed: 5, glide: 5, turn: -1, fade: 1 },
    avgRating: 4.8,
    numReviews: 92,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 5 },
      { rating: 4, count: 21 },
      { rating: 5, count: 65 },
    ],
    numSales: 198,
    countInStock: 26,
    description:
      'A straight flying midrange with excellent glide. GYRO technology provides a smooth, consistent flight.',
    sizes: [],
    colors: ['Teal', 'Orange', 'Blue', 'Pink'],
    reviews: [],
  },
  {
    name: 'Dynamic Discs EMac Truth',
    slug: toSlug('Dynamic Discs EMac Truth'),
    category: 'Midrange',
    images: [getImage(11), getImage(12)],
    tags: ['todays-deal'],
    discType: ['midrange'],
    isPublished: true,
    price: 14.99,
    listPrice: 17.99,
    brand: 'Dynamic Discs',
    plastic: 'Lucid',
    weight: 176,
    flightNumbers: { speed: 5, glide: 5, turn: 0, fade: 2 },
    avgRating: 4.6,
    numReviews: 64,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 5 },
      { rating: 4, count: 16 },
      { rating: 5, count: 40 },
    ],
    numSales: 145,
    countInStock: 29,
    description:
      'Eric McCabe signature midrange. A straight flyer with a pointed nose for reduced air resistance.',
    sizes: [],
    colors: ['Purple', 'Blue', 'Green', 'Yellow'],
    reviews: [],
  },
  // Putters
  {
    name: 'Innova Aviar',
    slug: toSlug('Innova Aviar'),
    category: 'Putter',
    images: [getImage(12), getImage(13)],
    tags: ['best-seller'],
    discType: ['putter'],
    isPublished: true,
    price: 12.99,
    listPrice: 0,
    brand: 'Innova',
    plastic: 'DX',
    weight: 175,
    flightNumbers: { speed: 2, glide: 3, turn: 0, fade: 1 },
    avgRating: 4.8,
    numReviews: 312,
    ratingDistribution: [
      { rating: 1, count: 3 },
      { rating: 2, count: 5 },
      { rating: 3, count: 12 },
      { rating: 4, count: 42 },
      { rating: 5, count: 250 },
    ],
    numSales: 678,
    countInStock: 56,
    description:
      'The original disc golf putter. Straight flight with a predictable fade. Used by more pros than any other putter.',
    sizes: [],
    colors: ['White', 'Blue', 'Yellow', 'Red', 'Green'],
    reviews: [],
  },
  {
    name: 'Discraft Luna',
    slug: toSlug('Discraft Luna'),
    category: 'Putter',
    images: [getImage(13), getImage(0)],
    tags: ['featured', 'best-seller'],
    discType: ['putter'],
    isPublished: true,
    price: 17.99,
    listPrice: 19.99,
    brand: 'Discraft',
    plastic: 'Jawbreaker',
    weight: 174,
    flightNumbers: { speed: 3, glide: 3, turn: 0, fade: 3 },
    avgRating: 4.9,
    numReviews: 198,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 6 },
      { rating: 4, count: 28 },
      { rating: 5, count: 161 },
    ],
    numSales: 423,
    countInStock: 34,
    description:
      'Paul McBeth signature putter. A comfortable beaded putter with a straight flight and soft fade.',
    sizes: [],
    colors: ['Blue', 'Orange', 'Green', 'Pink', 'White'],
    reviews: [],
  },
  {
    name: 'MVP Atom',
    slug: toSlug('MVP Atom'),
    category: 'Putter',
    images: [getImage(0), getImage(2)],
    tags: ['new-arrival'],
    discType: ['putter'],
    isPublished: true,
    price: 16.99,
    listPrice: 0,
    brand: 'MVP',
    plastic: 'Electron',
    weight: 171,
    flightNumbers: { speed: 3, glide: 3, turn: 0, fade: 1 },
    avgRating: 4.7,
    numReviews: 76,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 5 },
      { rating: 4, count: 18 },
      { rating: 5, count: 51 },
    ],
    numSales: 167,
    countInStock: 23,
    description:
      'A straight flying putter with GYRO technology. Excellent for both putting and approach shots.',
    sizes: [],
    colors: ['Teal', 'White', 'Blue', 'Orange'],
    reviews: [],
  },
  {
    name: 'Latitude 64 Pure',
    slug: toSlug('Latitude 64 Pure'),
    category: 'Putter',
    images: [getImage(1), getImage(3)],
    tags: ['todays-deal'],
    discType: ['putter'],
    isPublished: true,
    price: 11.99,
    listPrice: 14.99,
    brand: 'Latitude 64',
    plastic: 'Zero Medium',
    weight: 173,
    flightNumbers: { speed: 3, glide: 3, turn: 0, fade: 1 },
    avgRating: 4.6,
    numReviews: 89,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 3 },
      { rating: 3, count: 7 },
      { rating: 4, count: 22 },
      { rating: 5, count: 56 },
    ],
    numSales: 201,
    countInStock: 41,
    description:
      'A beadless straight flying putter with a comfortable grip. Great for beginners and experienced players.',
    sizes: [],
    colors: ['Yellow', 'White', 'Blue', 'Red'],
    reviews: [],
  },
  {
    name: 'Kastaplast Berg',
    slug: toSlug('Kastaplast Berg'),
    category: 'Putter',
    images: [getImage(2), getImage(4)],
    tags: ['featured'],
    discType: ['putter'],
    isPublished: true,
    price: 18.99,
    listPrice: 0,
    brand: 'Kastaplast',
    plastic: 'K1',
    weight: 175,
    flightNumbers: { speed: 1, glide: 1, turn: 0, fade: 2 },
    avgRating: 4.8,
    numReviews: 112,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 6 },
      { rating: 4, count: 24 },
      { rating: 5, count: 81 },
    ],
    numSales: 234,
    countInStock: 18,
    description:
      'An approach disc that stops on a dime. The Berg has almost no glide, making it perfect for windy conditions.',
    sizes: [],
    colors: ['Glow', 'Pink', 'Blue', 'Yellow'],
    reviews: [],
  },
  {
    name: 'Innova Wraith',
    slug: toSlug('Innova Wraith'),
    category: 'Distance Driver',
    images: [getImage(3), getImage(5)],
    tags: ['best-seller'],
    discType: ['distance driver'],
    isPublished: true,
    price: 17.99,
    listPrice: 20.99,
    brand: 'Innova',
    plastic: 'Star',
    weight: 175,
    flightNumbers: { speed: 11, glide: 5, turn: -1, fade: 3 },
    avgRating: 4.7,
    numReviews: 145,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 3 },
      { rating: 3, count: 9 },
      { rating: 4, count: 32 },
      { rating: 5, count: 100 },
    ],
    numSales: 312,
    countInStock: 27,
    description:
      'A controllable distance driver with good glide. Slightly less stable than the Destroyer, great for long turnovers.',
    sizes: [],
    colors: ['Red', 'Blue', 'Green', 'Yellow', 'Orange'],
    reviews: [],
  },
  {
    name: 'Discmania PD',
    slug: toSlug('Discmania PD'),
    category: 'Fairway Driver',
    images: [getImage(4), getImage(6)],
    tags: ['new-arrival', 'featured'],
    discType: ['fairway driver'],
    isPublished: true,
    price: 22.99,
    listPrice: 0,
    brand: 'Discmania',
    plastic: 'S-Line',
    weight: 175,
    flightNumbers: { speed: 10, glide: 4, turn: 0, fade: 3 },
    avgRating: 4.8,
    numReviews: 67,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 3 },
      { rating: 4, count: 14 },
      { rating: 5, count: 49 },
    ],
    numSales: 143,
    countInStock: 14,
    description:
      'The Power Driver. An overstable fairway that fights wind and delivers reliable fade every time.',
    sizes: [],
    colors: ['Blue', 'Red', 'White', 'Orange'],
    reviews: [],
  },
  {
    name: 'Prodigy M4',
    slug: toSlug('Prodigy M4'),
    category: 'Midrange',
    images: [getImage(5), getImage(7)],
    tags: ['todays-deal'],
    discType: ['midrange'],
    isPublished: true,
    price: 13.99,
    listPrice: 16.99,
    brand: 'Prodigy',
    plastic: '400',
    weight: 177,
    flightNumbers: { speed: 5, glide: 5, turn: -2, fade: 1 },
    avgRating: 4.5,
    numReviews: 54,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 5 },
      { rating: 4, count: 14 },
      { rating: 5, count: 32 },
    ],
    numSales: 118,
    countInStock: 33,
    description:
      'A straight to understable midrange with excellent glide. Great for beginners and turnover shots.',
    sizes: [],
    colors: ['Green', 'Yellow', 'Blue', 'Orange'],
    reviews: [],
  },
  {
    name: 'Westside Discs Harp',
    slug: toSlug('Westside Discs Harp'),
    category: 'Putter',
    images: [getImage(6), getImage(8)],
    tags: ['featured'],
    discType: ['putter'],
    isPublished: true,
    price: 15.99,
    listPrice: 0,
    brand: 'Westside Discs',
    plastic: 'VIP',
    weight: 174,
    flightNumbers: { speed: 4, glide: 3, turn: 0, fade: 3 },
    avgRating: 4.7,
    numReviews: 98,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 7 },
      { rating: 4, count: 23 },
      { rating: 5, count: 66 },
    ],
    numSales: 212,
    countInStock: 25,
    description:
      'An overstable approach disc that handles wind well. Great for forehand approaches and spike hyzers.',
    sizes: [],
    colors: ['Orange', 'Blue', 'White', 'Pink'],
    reviews: [],
  },
  {
    name: 'Infinite Discs Emperor',
    slug: toSlug('Infinite Discs Emperor'),
    category: 'Distance Driver',
    images: [getImage(7), getImage(9)],
    tags: ['new-arrival'],
    discType: ['distance driver'],
    isPublished: true,
    price: 16.99,
    listPrice: 19.99,
    brand: 'Infinite Discs',
    plastic: 'I-Blend',
    weight: 173,
    flightNumbers: { speed: 12, glide: 5, turn: -1, fade: 3 },
    avgRating: 4.4,
    numReviews: 38,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 4 },
      { rating: 4, count: 11 },
      { rating: 5, count: 20 },
    ],
    numSales: 87,
    countInStock: 21,
    description:
      'A max distance driver with a comfortable rim. Similar to the Destroyer but with a touch more glide.',
    sizes: [],
    colors: ['Purple', 'Blue', 'Green', 'Yellow'],
    reviews: [],
  },
]

const data: Data = {
  products,
  headerMenus: [
    {
      name: "Today's Deals",
      href: "/search?tag=todays-deal"
    },
    {
      name: "New Arrivals",
      href: "/search?tag=new-arrival"
    },
    {
      name: "Featured Discs",
      href: "/search?tag=featured"
    },
    {
      name: "Best Sellers",
      href: "/search?tag=best-seller"
    },
    {
      name: "Donate",
      href: "/donate"
    },
  ],
  carousels: [
    {
      title: "Premium Discs, Unbeatable Prices",
      buttonCaption: "Shop All Discs",
      image: '/icons/images/New Project.png',
      url: '/products',
      isPublished: true,
    },
    {
      title: "Give Your Discs a Second Life",
      buttonCaption: "Donate Now",
      image: '/icons/images/New Project2 (1).png',
      url: '/donate',
      isPublished: true,
    },
    {
      title: "Fresh Plastic Just Landed",
      buttonCaption: "Shop New Arrivals",
      image: '/icons/images/New Project3.png',
      url: '/search?tag=new-arrival',
      isPublished: true,
    }
  ]
}

export default data;
